import { MetadataRoute } from "next";
import { CITIES_SEED } from "@/data/cities-seed";
import { RANKING_META } from "@/lib/rankings";
import { GUIDES } from "@/data/guides";

const BASE_URL = process.env.NEXT_PUBLIC_BASE_URL ?? "https://meilleurville.fr";

export default function sitemap(): MetadataRoute.Sitemap {
  const SEO_PAIRS = [
    ["annecy", "grenoble"],
    ["nantes", "rennes"],
    ["bordeaux", "toulouse"],
    ["lyon", "grenoble"],
    ["montpellier", "nice"],
    ["nantes", "bordeaux"],
    ["rennes", "nantes"],
    ["nice", "aix-en-provence"],
    ["strasbourg", "lyon"],
    ["brest", "rennes"],
    ["toulouse", "montpellier"],
    ["angers", "nantes"],
    ["lille", "strasbourg"],
    ["bordeaux", "nantes"],
    ["lyon", "bordeaux"],
    ["grenoble", "annecy"],
    ["la-rochelle", "bordeaux"],
    ["pau", "biarritz"],
    ["caen", "rennes"],
    ["dijon", "strasbourg"],
    ["tours", "orleans"],
    ["annecy", "biarritz"],
    ["quimper", "brest"],
    ["valence", "grenoble"],
    ["lyon", "nice"],
    ["montpellier", "marseille"],
    ["besancon", "dijon"],
    ["toulon", "nice"],
    ["rouen", "caen"],
    ["perpignan", "montpellier"],
    ["vannes", "rennes"],
    ["chambery", "annecy"],
    ["nimes", "montpellier"],
    ["gap", "grenoble"],
    ["saint-malo", "rennes"],
    ["colmar", "strasbourg"],
    ["lorient", "brest"],
    ["bayonne", "bordeaux"],
    ["arles", "avignon"],
    ["angers", "le-mans"],
    ["metz", "nancy"],
    ["metz", "strasbourg"],
    ["nancy", "strasbourg"],
    ["saint-etienne", "lyon"],
    ["saint-etienne", "grenoble"],
    ["limoges", "bordeaux"],
    ["limoges", "poitiers"],
    ["amiens", "lille"],
    ["amiens", "rouen"],
    ["troyes", "reims"],
    ["troyes", "dijon"],
    ["tours", "angers"],
    ["pau", "bayonne"],
    ["clermont-ferrand", "lyon"],
    ["clermont-ferrand", "grenoble"],
    ["toulon", "marseille"],
    ["perpignan", "nimes"],
    ["avignon", "marseille"],
    ["caen", "rouen"],
    ["reims", "troyes"],
    ["dijon", "besancon"],
    ["poitiers", "tours"],
    ["le-havre", "rouen"],
    ["valence", "avignon"],
    ["frejus", "toulon"],
    ["colmar", "nancy"],
    ["angers", "tours"],
    ["nantes", "angers"],
    ["biarritz", "pau"],
    ["saint-malo", "brest"],
    ["quimper", "lorient"],
    ["vannes", "lorient"],
    ["cannes", "nice"],
    ["cannes", "marseille"],
    ["ajaccio", "nice"],
    ["mulhouse", "strasbourg"],
    ["mulhouse", "colmar"],
    ["dunkerque", "lille"],
    ["dunkerque", "boulogne-sur-mer"],
    ["cannes", "biarritz"],
    ["sete", "montpellier"],
    ["sete", "perpignan"],
    ["sete", "nimes"],
    ["beziers", "montpellier"],
    ["beziers", "nimes"],
    ["laval", "nantes"],
    ["laval", "rennes"],
    ["perigueux", "bordeaux"],
    ["ales", "nimes"],
    ["chartres", "orleans"],
    ["rodez", "toulouse"],
    ["rodez", "montpellier"],
    ["agen", "bordeaux"],
    ["agen", "toulouse"],
    ["macon", "lyon"],
    ["macon", "dijon"],
    ["bourg-en-bresse", "lyon"],
    ["bourg-en-bresse", "annecy"],
    ["evreux", "rouen"],
    ["evreux", "caen"],
    ["antibes", "nice"],
    ["antibes", "cannes"],
    ["thionville", "metz"],
    ["thionville", "nancy"],
    ["arras", "lille"],
    ["arras", "amiens"],
    ["carcassonne", "perpignan"],
    ["carcassonne", "toulouse"],
    ["bayeux", "caen"],
    ["saint-brieuc", "rennes"],
    ["saint-brieuc", "brest"],
    ["saint-nazaire", "nantes"],
    ["chalons-en-champagne", "reims"],
    ["auxerre", "dijon"],
    ["auxerre", "troyes"],
    ["belfort", "mulhouse"],
    ["belfort", "besancon"],
    ["vichy", "clermont-ferrand"],
    ["montauban", "toulouse"],
    ["montauban", "agen"],
    ["alencon", "caen"],
    ["alencon", "le-mans"],
    ["millau", "rodez"],
    ["millau", "montpellier"],
    ["cognac", "bordeaux"],
    ["cognac", "angouleme"],
    ["epinal", "nancy"],
    ["epinal", "metz"],
    ["montelimar", "valence"],
    ["montelimar", "avignon"],
    ["figeac", "cahors"],
    ["figeac", "rodez"],
    ["romans-sur-isere", "valence"],
    ["romans-sur-isere", "grenoble"],
    ["saintes", "rochefort"],
    ["saintes", "angouleme"],
    ["blois", "tours"],
    ["blois", "orleans"],
    ["chalon-sur-saone", "dijon"],
    ["chalon-sur-saone", "macon"],
    ["cholet", "nantes"],
    ["cholet", "angers"],
    ["draguignan", "nice"],
    ["draguignan", "toulon"],
    ["aix-les-bains", "annecy"],
    ["aix-les-bains", "chambery"],
    ["aix-les-bains", "thonon-les-bains"],
    ["bergerac", "bordeaux"],
    ["bergerac", "perigueux"],
    ["arcachon", "bordeaux"],
    ["arcachon", "biarritz"],
    ["thonon-les-bains", "annecy"],
    ["thonon-les-bains", "chambery"],
    ["salon-de-provence", "aix-en-provence"],
    ["salon-de-provence", "marseille"],
    ["martigues", "marseille"],
    ["martigues", "toulon"],
    ["calais", "boulogne-sur-mer"],
    ["calais", "dunkerque"],
    ["lens", "arras"],
    ["lens", "lille"],
    ["valenciennes", "lens"],
    ["valenciennes", "lille"],
    ["castres", "albi"],
    ["castres", "toulouse"],
    ["hyeres", "toulon"],
    ["hyeres", "nice"],
    ["haguenau", "strasbourg"],
    ["haguenau", "colmar"],
    ["roanne", "lyon"],
    ["roanne", "saint-etienne"],
    ["douai", "lens"],
    ["douai", "valenciennes"],
    ["cambrai", "valenciennes"],
    ["cambrai", "arras"],
    ["montbeliard", "belfort"],
    ["montbeliard", "besancon"],
    ["aurillac", "clermont-ferrand"],
    ["chatellerault", "poitiers"],
    ["chatellerault", "tours"],
    ["annemasse", "annecy"],
    ["annemasse", "thonon-les-bains"],
    ["compiegne", "amiens"],
    ["beauvais", "amiens"],
    ["beauvais", "rouen"],
    ["narbonne", "montpellier"],
    ["narbonne", "perpignan"],
    ["saint-quentin", "amiens"],
    ["saint-quentin", "reims"],
    ["selestat", "strasbourg"],
    ["selestat", "colmar"],
    ["bourges", "tours"],
    ["bourges", "orleans"],
    ["chateauroux", "tours"],
    ["chateauroux", "bourges"],
    ["brive-la-gaillarde", "perigueux"],
    ["brive-la-gaillarde", "bordeaux"],
    ["auch", "toulouse"],
    ["auch", "pau"],
    ["dole", "besancon"],
    ["dole", "dijon"],
    ["lannion", "brest"],
    ["lannion", "saint-brieuc"],
    ["paris", "lyon"],
    ["paris", "nantes"],
    ["paris", "bordeaux"],
    ["paris", "toulouse"],
    ["versailles", "vincennes"],
    ["versailles", "cergy"],
    ["boulogne-billancourt", "vincennes"],
    ["boulogne-billancourt", "montreuil"],
    ["montreuil", "vincennes"],
    ["cergy", "versailles"],
    ["neuilly-sur-seine", "vincennes"],
    ["neuilly-sur-seine", "versailles"],
    ["levallois-perret", "neuilly-sur-seine"],
    ["saint-germain-en-laye", "versailles"],
    ["saint-germain-en-laye", "fontainebleau"],
    ["fontainebleau", "versailles"],
    ["saint-denis", "montreuil"],
    ["issy-les-moulineaux", "boulogne-billancourt"],
  ];

  const staticRoutes: MetadataRoute.Sitemap = [
    { url: BASE_URL, lastModified: new Date(), changeFrequency: "daily", priority: 1.0 },
    { url: `${BASE_URL}/quiz`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.9 },
    { url: `${BASE_URL}/villes`, lastModified: new Date(), changeFrequency: "weekly", priority: 0.8 },
    { url: `${BASE_URL}/classements`, lastModified: new Date(), changeFrequency: "weekly", priority: 0.9 },
    { url: `${BASE_URL}/comparer`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: `${BASE_URL}/premium`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
    { url: `${BASE_URL}/methode`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.5 },
    { url: `${BASE_URL}/red-flags`, lastModified: new Date(), changeFrequency: "weekly", priority: 0.7 },
    { url: `${BASE_URL}/guides`, lastModified: new Date(), changeFrequency: "weekly", priority: 0.8 },
    { url: `${BASE_URL}/leaderboard`, lastModified: new Date(), changeFrequency: "weekly", priority: 0.7 },
    { url: `${BASE_URL}/about`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.5 },
    { url: `${BASE_URL}/contact`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.4 },
    { url: `${BASE_URL}/donnees`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
    { url: `${BASE_URL}/regions`, lastModified: new Date(), changeFrequency: "weekly", priority: 0.7 },
    { url: `${BASE_URL}/departements`, lastModified: new Date(), changeFrequency: "weekly", priority: 0.7 },
    { url: `${BASE_URL}/carte`, lastModified: new Date(), changeFrequency: "weekly", priority: 0.7 },
    { url: `${BASE_URL}/faq`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.5 },
    { url: `${BASE_URL}/mentions-legales`, lastModified: new Date(), changeFrequency: "yearly", priority: 0.3 },
    { url: `${BASE_URL}/confidentialite`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.3 },
    { url: `${BASE_URL}/cgu`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.3 },
    ...Object.keys(RANKING_META).map((slug) => ({
      url: `${BASE_URL}/classements/${slug}`,
      lastModified: new Date(),
      changeFrequency: "weekly" as const,
      priority: 0.8,
    })),
    ...SEO_PAIRS.map(([a, b]) => ({
      url: `${BASE_URL}/comparer/${a}-vs-${b}`,
      lastModified: new Date(),
      changeFrequency: "weekly" as const,
      priority: 0.6,
    })),
  ];

  const guideRoutes: MetadataRoute.Sitemap = GUIDES.map((g) => ({
    url: `${BASE_URL}/guides/${g.slug}`,
    lastModified: new Date(g.updatedAt),
    changeFrequency: "monthly" as const,
    priority: 0.7,
  }));

  const regions = [...new Set(CITIES_SEED.map((c) => c.region))];
  const regionRoutes: MetadataRoute.Sitemap = regions.map((r) => ({
    url: `${BASE_URL}/regions/${r.toLowerCase().normalize("NFD").replace(/[̀-ͯ]/g, "").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "")}`,
    lastModified: new Date(),
    changeFrequency: "weekly" as const,
    priority: 0.7,
  }));

  const depts = [...new Set(CITIES_SEED.map((c) => c.department))];
  const deptRoutes: MetadataRoute.Sitemap = depts.map((d) => ({
    url: `${BASE_URL}/departements/${d.toLowerCase().normalize("NFD").replace(/[̀-ͯ]/g, "").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "")}`,
    lastModified: new Date(),
    changeFrequency: "weekly" as const,
    priority: 0.65,
  }));

  const cityRoutes: MetadataRoute.Sitemap = CITIES_SEED.flatMap((city) => [
    {
      url: `${BASE_URL}/villes/${city.slug}`,
      lastModified: new Date(),
      changeFrequency: "weekly" as const,
      priority: 0.7,
    },
    {
      url: `${BASE_URL}/villes/${city.slug}/quartiers`,
      lastModified: new Date(),
      changeFrequency: "monthly" as const,
      priority: 0.5,
    },
  ]);

  return [...staticRoutes, ...guideRoutes, ...regionRoutes, ...deptRoutes, ...cityRoutes];
}
