import { MetadataRoute } from "next";
import { CITIES_SEED } from "@/data/cities-seed";
import { RANKING_META } from "@/lib/rankings";
import { GUIDES } from "@/data/guides";

const BASE_URL = process.env.NEXT_PUBLIC_BASE_URL ?? "https://meilleurville.fr";

export default function sitemap(): MetadataRoute.Sitemap {
  const SEO_PAIRS = [
    ["annecy", "grenoble"],
    ["nantes", "rennes"],
    ["bordeaux", "toulouse"],
    ["lyon", "grenoble"],
    ["montpellier", "nice"],
    ["nantes", "bordeaux"],
    ["rennes", "nantes"],
    ["nice", "aix-en-provence"],
    ["strasbourg", "lyon"],
    ["brest", "rennes"],
    ["toulouse", "montpellier"],
    ["angers", "nantes"],
    ["lille", "strasbourg"],
    ["bordeaux", "nantes"],
    ["lyon", "bordeaux"],
    ["grenoble", "annecy"],
    ["la-rochelle", "bordeaux"],
    ["pau", "biarritz"],
    ["caen", "rennes"],
    ["dijon", "strasbourg"],
    ["tours", "orleans"],
    ["annecy", "biarritz"],
    ["quimper", "brest"],
    ["valence", "grenoble"],
    ["lyon", "nice"],
    ["montpellier", "marseille"],
    ["besancon", "dijon"],
    ["toulon", "nice"],
    ["rouen", "caen"],
    ["perpignan", "montpellier"],
    ["vannes", "rennes"],
    ["chambery", "annecy"],
    ["nimes", "montpellier"],
    ["gap", "grenoble"],
    ["saint-malo", "rennes"],
    ["colmar", "strasbourg"],
    ["lorient", "brest"],
    ["bayonne", "bordeaux"],
    ["arles", "avignon"],
    ["angers", "le-mans"],
    ["metz", "nancy"],
    ["metz", "strasbourg"],
    ["nancy", "strasbourg"],
    ["saint-etienne", "lyon"],
    ["saint-etienne", "grenoble"],
    ["limoges", "bordeaux"],
    ["limoges", "poitiers"],
    ["amiens", "lille"],
    ["amiens", "rouen"],
    ["troyes", "reims"],
    ["troyes", "dijon"],
    ["tours", "angers"],
    ["pau", "bayonne"],
    ["clermont-ferrand", "lyon"],
    ["clermont-ferrand", "grenoble"],
    ["toulon", "marseille"],
    ["perpignan", "nimes"],
    ["avignon", "marseille"],
    ["caen", "rouen"],
    ["reims", "troyes"],
    ["dijon", "besancon"],
    ["poitiers", "tours"],
    ["le-havre", "rouen"],
    ["valence", "avignon"],
    ["frejus", "toulon"],
    ["colmar", "nancy"],
    ["angers", "tours"],
    ["nantes", "angers"],
    ["biarritz", "pau"],
    ["saint-malo", "brest"],
    ["quimper", "lorient"],
    ["vannes", "lorient"],
    ["cannes", "nice"],
    ["cannes", "marseille"],
    ["ajaccio", "nice"],
    ["mulhouse", "strasbourg"],
    ["mulhouse", "colmar"],
    ["dunkerque", "lille"],
    ["dunkerque", "boulogne-sur-mer"],
    ["cannes", "biarritz"],
    ["sete", "montpellier"],
    ["sete", "perpignan"],
    ["sete", "nimes"],
    ["beziers", "montpellier"],
    ["beziers", "nimes"],
    ["laval", "nantes"],
    ["laval", "rennes"],
    ["perigueux", "bordeaux"],
    ["ales", "nimes"],
    ["chartres", "orleans"],
    ["rodez", "toulouse"],
    ["rodez", "montpellier"],
    ["agen", "bordeaux"],
    ["agen", "toulouse"],
    ["macon", "lyon"],
    ["macon", "dijon"],
    ["bourg-en-bresse", "lyon"],
    ["bourg-en-bresse", "annecy"],
    ["evreux", "rouen"],
    ["evreux", "caen"],
    ["antibes", "nice"],
    ["antibes", "cannes"],
    ["thionville", "metz"],
    ["thionville", "nancy"],
    ["arras", "lille"],
    ["arras", "amiens"],
    ["carcassonne", "perpignan"],
    ["carcassonne", "toulouse"],
    ["bayeux", "caen"],
    ["saint-brieuc", "rennes"],
    ["saint-brieuc", "brest"],
    ["saint-nazaire", "nantes"],
    ["chalons-en-champagne", "reims"],
    ["auxerre", "dijon"],
    ["auxerre", "troyes"],
    ["belfort", "mulhouse"],
    ["belfort", "besancon"],
    ["vichy", "clermont-ferrand"],
    ["montauban", "toulouse"],
    ["montauban", "agen"],
    ["alencon", "caen"],
    ["alencon", "le-mans"],
    ["millau", "rodez"],
    ["millau", "montpellier"],
    ["cognac", "bordeaux"],
    ["cognac", "angouleme"],
    ["epinal", "nancy"],
    ["epinal", "metz"],
    ["montelimar", "valence"],
    ["montelimar", "avignon"],
    ["figeac", "cahors"],
    ["figeac", "rodez"],
    ["romans-sur-isere", "valence"],
    ["romans-sur-isere", "grenoble"],
    ["saintes", "rochefort"],
    ["saintes", "angouleme"],
    ["blois", "tours"],
    ["blois", "orleans"],
    ["chalon-sur-saone", "dijon"],
    ["chalon-sur-saone", "macon"],
    ["cholet", "nantes"],
    ["cholet", "angers"],
    ["draguignan", "nice"],
    ["draguignan", "toulon"],
    ["aix-les-bains", "annecy"],
    ["aix-les-bains", "chambery"],
    ["aix-les-bains", "thonon-les-bains"],
    ["bergerac", "bordeaux"],
    ["bergerac", "perigueux"],
    ["arcachon", "bordeaux"],
    ["arcachon", "biarritz"],
    ["thonon-les-bains", "annecy"],
    ["thonon-les-bains", "chambery"],
    ["salon-de-provence", "aix-en-provence"],
    ["salon-de-provence", "marseille"],
    ["martigues", "marseille"],
    ["martigues", "toulon"],
    ["calais", "boulogne-sur-mer"],
    ["calais", "dunkerque"],
    ["lens", "arras"],
    ["lens", "lille"],
    ["valenciennes", "lens"],
    ["valenciennes", "lille"],
    ["castres", "albi"],
    ["castres", "toulouse"],
    ["hyeres", "toulon"],
    ["hyeres", "nice"],
    ["haguenau", "strasbourg"],
    ["haguenau", "colmar"],
    ["roanne", "lyon"],
    ["roanne", "saint-etienne"],
    ["douai", "lens"],
    ["douai", "valenciennes"],
    ["cambrai", "valenciennes"],
    ["cambrai", "arras"],
    ["montbeliard", "belfort"],
    ["montbeliard", "besancon"],
    ["aurillac", "clermont-ferrand"],
    ["chatellerault", "poitiers"],
    ["chatellerault", "tours"],
    ["annemasse", "annecy"],
    ["annemasse", "thonon-les-bains"],
    ["compiegne", "amiens"],
    ["beauvais", "amiens"],
    ["beauvais", "rouen"],
    ["narbonne", "montpellier"],
    ["narbonne", "perpignan"],
    ["saint-quentin", "amiens"],
    ["saint-quentin", "reims"],
    ["selestat", "strasbourg"],
    ["selestat", "colmar"],
    ["bourges", "tours"],
    ["bourges", "orleans"],
    ["chateauroux", "tours"],
    ["chateauroux", "bourges"],
    ["brive-la-gaillarde", "perigueux"],
    ["brive-la-gaillarde", "bordeaux"],
    ["auch", "toulouse"],
    ["auch", "pau"],
    ["dole", "besancon"],
    ["dole", "dijon"],
    ["lannion", "brest"],
    ["lannion", "saint-brieuc"],
    ["paris", "lyon"],
    ["paris", "nantes"],
    ["paris", "bordeaux"],
    ["paris", "toulouse"],
    ["versailles", "vincennes"],
    ["versailles", "cergy"],
    ["boulogne-billancourt", "vincennes"],
    ["boulogne-billancourt", "montreuil"],
    ["montreuil", "vincennes"],
    ["cergy", "versailles"],
    ["neuilly-sur-seine", "vincennes"],
    ["neuilly-sur-seine", "versailles"],
    ["levallois-perret", "neuilly-sur-seine"],
    ["saint-germain-en-laye", "versailles"],
    ["saint-germain-en-laye", "fontainebleau"],
    ["fontainebleau", "versailles"],
    ["saint-denis", "montreuil"],
    ["issy-les-moulineaux", "boulogne-billancourt"],
    ["bastia", "ajaccio"],
    ["pantin", "montreuil"],
    ["pantin", "saint-denis"],
    ["ivry-sur-seine", "montreuil"],
    ["creteil", "vincennes"],
    ["rueil-malmaison", "versailles"],
    ["rueil-malmaison", "saint-germain-en-laye"],
    ["colombes", "argenteuil"],
    ["argenteuil", "cergy"],
    ["marseille", "toulouse"],
    ["paris", "marseille"],
    ["paris", "strasbourg"],
    ["paris", "rennes"],
    ["paris", "nice"],
    ["lyon", "nantes"],
    ["bordeaux", "lyon"],
    ["nantes", "bordeaux"],
    ["nanterre", "cergy"],
    ["courbevoie", "levallois-perret"],
    ["nanterre", "courbevoie"],
    ["vitry-sur-seine", "ivry-sur-seine"],
    ["noisy-le-grand", "creteil"],
    ["evry-courcouronnes", "cergy"],
    ["menton", "nice"],
    ["menton", "antibes"],
    ["la-roche-sur-yon", "les-sables-d-olonne"],
    ["les-sables-d-olonne", "nantes"],
    ["la-roche-sur-yon", "nantes"],
    ["dax", "pau"],
    ["dax", "bayonne"],
    ["mont-de-marsan", "dax"],
    ["le-puy-en-velay", "clermont-ferrand"],
    ["le-puy-en-velay", "mende"],
    ["villeurbanne", "lyon"],
    ["villeurbanne", "grenoble"],
    ["manosque", "aix-en-provence"],
    ["manosque", "gap"],
    ["nevers", "auxerre"],
    ["nevers", "dijon"],
    ["verdun", "metz"],
    ["aubenas", "valence"],
    ["aubenas", "montélimar"],
    ["pamiers", "foix"],
    ["pamiers", "toulouse"],
    ["saumur", "angers"],
    ["saumur", "tours"],
    ["briancon", "gap"],
    ["briancon", "grenoble"],
    ["epernay", "reims"],
    ["epernay", "chalons-en-champagne"],
    ["la-ciotat", "cassis"],
    ["la-ciotat", "marseille"],
    ["saint-raphael", "frejus"],
    ["saint-raphael", "cannes"],
    ["anglet", "biarritz"],
    ["anglet", "bayonne"],
    ["honfleur", "caen"],
    ["honfleur", "rouen"],
    ["cassis", "marseille"],
    ["cassis", "la-ciotat"],
    ["foix", "pamiers"],
    ["foix", "toulouse"],
    ["royan", "la-rochelle"],
    ["royan", "saintes"],
    ["grasse", "nice"],
    ["grasse", "cannes"],
    ["concarneau", "quimper"],
    ["concarneau", "lorient"],
    ["saint-jean-de-luz", "biarritz"],
    ["saint-jean-de-luz", "bayonne"],
    ["sanary-sur-mer", "toulon"],
    ["sanary-sur-mer", "hyeres"],
    ["dinan", "saint-brieuc"],
    ["dinan", "saint-malo"],
    ["hendaye", "saint-jean-de-luz"],
    ["hendaye", "biarritz"],
    ["vitre", "rennes"],
    ["vitre", "laval"],
    ["la-baule", "saint-nazaire"],
    ["la-baule", "nantes"],
    ["mende", "aurillac"],
    ["mende", "millau"],
    ["amboise", "tours"],
    ["amboise", "blois"],
    ["amboise", "angers"],
    ["orange", "avignon"],
    ["orange", "nimes"],
    ["vienne", "lyon"],
    ["vienne", "grenoble"],
    ["granville", "caen"],
    ["granville", "cherbourg"],
    ["frejus", "saint-raphael"],
    ["frejus", "draguignan"],
    ["menton", "nice"],
    ["menton", "antibes"],
    ["dinard", "saint-malo"],
    ["dinard", "saint-brieuc"],
    ["collioure", "perpignan"],
    ["collioure", "sete"],
    ["senlis", "compiegne"],
    ["senlis", "beauvais"],
    ["morlaix", "brest"],
    ["morlaix", "quimper"],
    ["provins", "fontainebleau"],
    ["provins", "versailles"],
    ["gex", "annecy"],
    ["gex", "belfort"],
    ["saint-tropez", "toulon"],
    ["saint-tropez", "frejus"],
    ["hossegor", "biarritz"],
    ["hossegor", "dax"],
    ["obernai", "strasbourg"],
    ["obernai", "colmar"],
    ["cagnes-sur-mer", "nice"],
    ["cagnes-sur-mer", "antibes"],
    ["noirmoutier", "saint-nazaire"],
    ["noirmoutier", "les-sables-d-olonne"],
    ["carnac", "vannes"],
    ["carnac", "lorient"],
    ["ile-de-re", "la-rochelle"],
    ["ile-de-re", "royan"],
    ["quiberon", "carnac"],
    ["quiberon", "vannes"],
    ["pezenas", "montpellier"],
    ["pezenas", "beziers"],
    ["agde", "sete"],
    ["agde", "montpellier"],
    ["douarnenez", "quimper"],
    ["douarnenez", "brest"],
    ["biscarrosse", "hossegor"],
    ["biscarrosse", "arcachon"],
    ["saint-remy-de-provence", "arles"],
    ["saint-remy-de-provence", "aix-en-provence"],
    ["gordes", "avignon"],
    ["gordes", "arles"],
    ["sisteron", "gap"],
    ["sisteron", "manosque"],
    ["saint-paul-de-vence", "nice"],
    ["saint-paul-de-vence", "antibes"],
    ["valbonne", "cannes"],
    ["valbonne", "antibes"],
    ["ceret", "perpignan"],
    ["ceret", "collioure"],
    ["carpentras", "avignon"],
    ["carpentras", "orange"],
    ["apt", "avignon"],
    ["apt", "gordes"],
    ["aubagne", "marseille"],
    ["aubagne", "aix-en-provence"],
    ["sainte-maxime", "saint-tropez"],
    ["sainte-maxime", "frejus"],
    ["digne-les-bains", "gap"],
    ["digne-les-bains", "sisteron"],
    ["vaison-la-romaine", "avignon"],
    ["vaison-la-romaine", "orange"],
    ["albertville", "chambery"],
    ["albertville", "annecy"],
    ["evian-les-bains", "annecy"],
    ["evian-les-bains", "thonon-les-bains"],
    ["issoire", "clermont-ferrand"],
    ["issoire", "vichy"],
    ["moulins", "vichy"],
    ["moulins", "clermont-ferrand"],
    ["tulle", "brive-la-gaillarde"],
    ["tulle", "limoges"],
    ["pontarlier", "besancon"],
    ["pontarlier", "belfort"],
    ["challans", "la-roche-sur-yon"],
    ["challans", "les-sables-d-olonne"],
    ["fontenay-le-comte", "niort"],
    ["fontenay-le-comte", "la-roche-sur-yon"],
    ["vendome", "blois"],
    ["vendome", "tours"],
    ["vierzon", "bourges"],
    ["vierzon", "chateauroux"],
    ["montargis", "orleans"],
    ["montargis", "fontainebleau"],
    ["gien", "orleans"],
    ["gien", "saumur"],
    ["lourdes", "tarbes"],
    ["lourdes", "pau"],
    ["sarlat-la-caneda", "perigueux"],
    ["sarlat-la-caneda", "bergerac"],
    ["marmande", "agen"],
    ["marmande", "bordeaux"],
    ["limoux", "carcassonne"],
    ["limoux", "narbonne"],
    ["gueret", "limoges"],
    ["gueret", "brive-la-gaillarde"],
    ["saint-gaudens", "tarbes"],
    ["saint-gaudens", "toulouse"],
    ["dieppe", "rouen"],
    ["dieppe", "le-havre"],
    ["saint-lo", "caen"],
    ["saint-lo", "cherbourg"],
    ["parthenay", "niort"],
    ["parthenay", "poitiers"],
    ["beaune", "dijon"],
    ["beaune", "chalon-sur-saone"],
    ["autun", "dijon"],
    ["autun", "macon"],
    ["saverne", "strasbourg"],
    ["saverne", "obernai"],
    ["laon", "reims"],
    ["laon", "amiens"],
    ["vesoul", "besancon"],
    ["vesoul", "belfort"],
    ["chaumont", "troyes"],
    ["chaumont", "epernay"],
    ["chinon", "tours"],
    ["chinon", "saumur"],
    ["saint-die-des-vosges", "epinal"],
    ["saint-die-des-vosges", "nancy"],
    ["villefranche-de-rouergue", "rodez"],
    ["villefranche-de-rouergue", "cahors"],
    ["riom", "clermont-ferrand"],
    ["riom", "vichy"],
    ["thiers", "clermont-ferrand"],
    ["thiers", "riom"],
    ["oyonnax", "bourg-en-bresse"],
    ["oyonnax", "annecy"],
    ["cluses", "annecy"],
    ["cluses", "albertville"],
    ["rumilly", "annecy"],
    ["rumilly", "chambery"],
    ["annonay", "saint-etienne"],
    ["annonay", "vienne"],
    ["lons-le-saunier", "dole"],
    ["lons-le-saunier", "besancon"],
    ["saint-flour", "aurillac"],
    ["saint-flour", "issoire"],
    ["bar-le-duc", "verdun"],
    ["bar-le-duc", "nancy"],
    ["aubusson", "gueret"],
    ["langres", "chaumont"],
    ["langres", "dijon"],
    ["guingamp", "saint-brieuc"],
    ["guingamp", "morlaix"],
    ["flers", "alencon"],
    ["flers", "caen"],
    ["la-fleche", "le-mans"],
    ["la-fleche", "angers"],
    ["cosne-cours-sur-loire", "nevers"],
    ["cosne-cours-sur-loire", "auxerre"],
    ["sens", "auxerre"],
    ["condom", "auch"],
    ["moissac", "montauban"],
    ["moissac", "agen"],
    ["brioude", "le-puy-en-velay"],
    ["brioude", "issoire"],
    ["issoudun", "chateauroux"],
    ["issoudun", "bourges"],
    ["abbeville", "amiens"],
    ["abbeville", "dieppe"],
    ["les-andelys", "rouen"],
    ["les-andelys", "evreux"],
    ["dreux", "chartres"],
    ["florac-trois-rivieres", "mende"],
    ["sedan", "charleville-mezieres"],
    ["sedan", "verdun"],
    ["bar-sur-aube", "troyes"],
    ["gray", "vesoul"],
    ["gray", "besancon"],
    ["saint-yrieix-la-perche", "limoges"],
    ["mayenne", "laval"],
    ["pont-a-mousson", "nancy"],
    ["pont-a-mousson", "metz"],
    ["etampes", "evry-courcouronnes"],
    ["etampes", "chartres"],
    ["soissons", "laon"],
    ["villefranche-sur-saone", "lyon"],
    ["villefranche-sur-saone", "macon"],
    ["montbard", "beaune"],
    ["montbard", "dijon"],
    ["paray-le-monial", "chalon-sur-saone"],
    ["semur-en-auxois", "beaune"],
    ["semur-en-auxois", "dijon"],
    ["villeneuve-sur-lot", "agen"],
    ["villeneuve-sur-lot", "marmande"],
    ["gourdon", "cahors"],
    ["gourdon", "figeac"],
    ["castelsarrasin", "moissac"],
    ["castelsarrasin", "montauban"],
    ["sarrebourg", "metz"],
    ["longwy", "nancy"],
    ["saint-amand-montrond", "bourges"],
    ["saint-amand-montrond", "vierzon"],
    ["bressuire", "niort"],
    ["bressuire", "parthenay"],
    ["ussel", "brive-la-gaillarde"],
    ["ussel", "tulle"],
    ["montbrison", "saint-etienne"],
    ["montbrison", "roanne"],
    ["pontoise", "cergy"],
    ["pontoise", "argenteuil"],
    ["romorantin-lanthenay", "blois"],
    ["romorantin-lanthenay", "vendome"],
    ["joigny", "auxerre"],
    ["joigny", "sens"],
    ["privas", "aubenas"],
    ["privas", "annonay"],
    ["bagnols-sur-ceze", "nimes"],
    ["bagnols-sur-ceze", "ales"],
    ["muret", "toulouse"],
    ["muret", "saint-gaudens"],
    ["meaux", "fontainebleau"],
    ["meaux", "provins"],
    ["bourgoin-jallieu", "grenoble"],
    ["bourgoin-jallieu", "vienne"],
    ["gaillac", "albi"],
    ["gaillac", "castres"],
    ["romilly-sur-seine", "troyes"],
    ["romilly-sur-seine", "bar-sur-aube"],
    ["saint-dizier", "chaumont"],
    ["saint-dizier", "langres"],
    ["chateaudun", "chartres"],
    ["chateaudun", "dreux"],
    ["venissieux", "lyon"],
    ["venissieux", "villeurbanne"],
    ["chateau-gontier-sur-mayenne", "laval"],
    ["chateau-gontier-sur-mayenne", "mayenne"],
    ["rambouillet", "versailles"],
    ["rambouillet", "saint-germain-en-laye"],
    ["massy", "evry-courcouronnes"],
    ["massy", "etampes"],
    ["argentan", "alencon"],
    ["argentan", "flers"],
    ["gerardmer", "epinal"],
    ["gerardmer", "saint-die-des-vosges"],
    ["guebwiller", "colmar"],
    ["guebwiller", "mulhouse"],
    ["saint-claude", "dole"],
    ["saint-claude", "lons-le-saunier"],
    ["sable-sur-sarthe", "le-mans"],
    ["sable-sur-sarthe", "la-fleche"],
    ["louviers", "evreux"],
    ["louviers", "les-andelys"],
    ["bagneres-de-bigorre", "tarbes"],
    ["bagneres-de-bigorre", "lourdes"],
    ["lure", "vesoul"],
    ["lure", "gray"],
    ["peronne", "amiens"],
    ["peronne", "abbeville"],
    ["le-blanc", "chateauroux"],
    ["le-blanc", "issoudun"],
    ["montmorillon", "poitiers"],
    ["montmorillon", "chatellerault"],
  ];

  const staticRoutes: MetadataRoute.Sitemap = [
    { url: BASE_URL, lastModified: new Date(), changeFrequency: "daily", priority: 1.0 },
    { url: `${BASE_URL}/quiz`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.9 },
    { url: `${BASE_URL}/villes`, lastModified: new Date(), changeFrequency: "weekly", priority: 0.8 },
    { url: `${BASE_URL}/classements`, lastModified: new Date(), changeFrequency: "weekly", priority: 0.9 },
    { url: `${BASE_URL}/comparer`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: `${BASE_URL}/premium`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
    { url: `${BASE_URL}/methode`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.5 },
    { url: `${BASE_URL}/red-flags`, lastModified: new Date(), changeFrequency: "weekly", priority: 0.7 },
    { url: `${BASE_URL}/guides`, lastModified: new Date(), changeFrequency: "weekly", priority: 0.8 },
    { url: `${BASE_URL}/leaderboard`, lastModified: new Date(), changeFrequency: "weekly", priority: 0.7 },
    { url: `${BASE_URL}/about`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.5 },
    { url: `${BASE_URL}/contact`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.4 },
    { url: `${BASE_URL}/donnees`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
    { url: `${BASE_URL}/regions`, lastModified: new Date(), changeFrequency: "weekly", priority: 0.7 },
    { url: `${BASE_URL}/departements`, lastModified: new Date(), changeFrequency: "weekly", priority: 0.7 },
    { url: `${BASE_URL}/carte`, lastModified: new Date(), changeFrequency: "weekly", priority: 0.7 },
    { url: `${BASE_URL}/faq`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.5 },
    { url: `${BASE_URL}/mentions-legales`, lastModified: new Date(), changeFrequency: "yearly", priority: 0.3 },
    { url: `${BASE_URL}/confidentialite`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.3 },
    { url: `${BASE_URL}/cgu`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.3 },
    ...Object.keys(RANKING_META).map((slug) => ({
      url: `${BASE_URL}/classements/${slug}`,
      lastModified: new Date(),
      changeFrequency: "weekly" as const,
      priority: 0.8,
    })),
    ...SEO_PAIRS.map(([a, b]) => ({
      url: `${BASE_URL}/comparer/${a}-vs-${b}`,
      lastModified: new Date(),
      changeFrequency: "weekly" as const,
      priority: 0.6,
    })),
  ];

  const guideRoutes: MetadataRoute.Sitemap = GUIDES.map((g) => ({
    url: `${BASE_URL}/guides/${g.slug}`,
    lastModified: new Date(g.updatedAt),
    changeFrequency: "monthly" as const,
    priority: 0.7,
  }));

  const regions = [...new Set(CITIES_SEED.map((c) => c.region))];
  const regionRoutes: MetadataRoute.Sitemap = regions.map((r) => ({
    url: `${BASE_URL}/regions/${r.toLowerCase().normalize("NFD").replace(/[̀-ͯ]/g, "").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "")}`,
    lastModified: new Date(),
    changeFrequency: "weekly" as const,
    priority: 0.7,
  }));

  const depts = [...new Set(CITIES_SEED.map((c) => c.department))];
  const deptRoutes: MetadataRoute.Sitemap = depts.map((d) => ({
    url: `${BASE_URL}/departements/${d.toLowerCase().normalize("NFD").replace(/[̀-ͯ]/g, "").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "")}`,
    lastModified: new Date(),
    changeFrequency: "weekly" as const,
    priority: 0.65,
  }));

  const cityRoutes: MetadataRoute.Sitemap = CITIES_SEED.flatMap((city) => [
    {
      url: `${BASE_URL}/villes/${city.slug}`,
      lastModified: new Date(),
      changeFrequency: "weekly" as const,
      priority: 0.7,
    },
    {
      url: `${BASE_URL}/villes/${city.slug}/quartiers`,
      lastModified: new Date(),
      changeFrequency: "monthly" as const,
      priority: 0.5,
    },
  ]);

  return [...staticRoutes, ...guideRoutes, ...regionRoutes, ...deptRoutes, ...cityRoutes];
}
