/**
 * English labels for the seed's French `characterTags`, used by the EN city
 * page hero (bestcitiesinfrance.com).
 *
 * Why a map and not a translation of every tag (audit 2026-10-09): the seed
 * carries 1 163 distinct free-text tags across 3 021 uses, and the EN city page
 * printed them as-is — "étudiant dynamique breton tech vélo" above the H1 of
 * every English city page. The 110 most frequent tags cover about half of all
 * uses; the EN hero shows a tag only when it has a reviewed English label here
 * and drops the rest, because a missing decorative chip costs nothing and a
 * French one on the English site reads as an unfinished page. Proper nouns
 * (rivers, regions, transit lines, UNESCO) map to themselves. French-only
 * programme acronyms (ANRU) are deliberately absent: they mean nothing to the
 * EN reader.
 *
 * Keys are matched case-insensitively. FR pages never read this file.
 */
const TAG_LABELS_EN: Record<string, string> = {
  abordable: "affordable",
  "très abordable": "very affordable",
  calme: "quiet",
  "résidentiel": "residential",
  "résidentiel haut de gamme": "upmarket residential",
  patrimoine: "heritage",
  nature: "nature",
  "banlieue parisienne": "Paris suburbs",
  "banlieue parisienne sud": "south Paris suburbs",
  "banlieue parisienne est": "east Paris suburbs",
  "banlieue bordelaise": "Bordeaux suburbs",
  "banlieue lyonnaise": "Lyon suburbs",
  "limitrophe paris": "borders Paris",
  "paris-proche": "close to Paris",
  soleil: "sunny",
  gastronomie: "food scene",
  mer: "sea",
  accessible: "well connected",
  dynamique: "lively",
  populaire: "working-class",
  tourisme: "tourism",
  famille: "family",
  familial: "family-friendly",
  historique: "historic",
  histoire: "history",
  drom: "overseas France",
  "médiéval": "medieval",
  "sous-préfecture": "sub-prefecture",
  "préfecture": "prefecture",
  montagne: "mountains",
  "marché": "market",
  "authenticité": "authentic",
  authentique: "authentic",
  "château": "château",
  "méditerranée": "Mediterranean",
  "étudiant": "student",
  universitaire: "university town",
  "université": "university",
  industrie: "industry",
  industriel: "industrial",
  "cathédrale": "cathedral",
  artisanat: "crafts",
  "forêt": "forest",
  plage: "beach",
  plages: "beaches",
  prestige: "prestige",
  port: "port",
  tertiaire: "office jobs",
  "vélo": "cycling",
  atlantique: "Atlantic",
  tropical: "tropical",
  surf: "surf",
  vignoble: "vineyards",
  vin: "wine",
  "pêche": "fishing",
  pavillonnaire: "suburban houses",
  "ville nouvelle": "new town",
  rugby: "rugby",
  remparts: "ramparts",
  "océan indien": "Indian Ocean",
  "caraïbes": "Caribbean",
  tech: "tech",
  bourgeois: "well-heeled",
  altitude: "high altitude",
  "balnéaire": "seaside resort",
  art: "art",
  frontalier: "border town",
  sport: "sport",
  verdoyant: "green",
  dense: "dense",
  reconversion: "regeneration",
  premium: "premium",
  bocage: "hedgerow country",
  multiculturel: "multicultural",
  culture: "culture",
  culturel: "cultural",
  retraite: "retirement",
  lac: "lake",
  festival: "festivals",
  luxe: "luxury",
  alsacien: "Alsatian",
  // Proper nouns — kept as written.
  seine: "Seine",
  loire: "Loire",
  marne: "Marne",
  "rhône": "Rhône",
  garonne: "Garonne",
  provence: "Provence",
  normandie: "Normandy",
  bretagne: "Brittany",
  bourgogne: "Burgundy",
  alsace: "Alsace",
  moselle: "Moselle",
  jura: "Jura",
  luberon: "Luberon",
  "pyrénées": "Pyrenees",
  unesco: "UNESCO",
  "seine-saint-denis": "Seine-Saint-Denis",
  "hauts-de-seine": "Hauts-de-Seine",
  "saint-quentin-en-yvelines": "Saint-Quentin-en-Yvelines",
  "rer a": "RER A",
  "rer b": "RER B",
  "rer c": "RER C",
  "rer d": "RER D",
  "rer e": "RER E",
  "transilien n": "Transilien N",
  "tramway t1": "tram T1",
  "tramway t2": "tram T2",
  "tramway t6": "tram T6",
  "tramway a": "tram A",
};

/** English label for a seed tag, or null when the tag has no reviewed EN label. */
export function tagLabelEn(tag: string): string | null {
  return TAG_LABELS_EN[tag.trim().toLowerCase()] ?? null;
}
